### ISSUE TITLE
Deleting `message['type']` in one consumer prevents delivery to other consumers

### ISSUE THREAD

**Issue by zozoh94** [CJWorkbench/channels_rabbitmq#17]
I'm a bit confused, is it possible with your layer to use AsyncHttpConsumer (sse) with groups. I try to deal with it but I always have just one consumer consuming events (that I send with channel_layer.group_send and in my handle method of the consumer I use group_add).
Thanks for help and details.

Regards

**Comment by adamhooper** [comment]
Yes, groups are battle-tested.

Could you please describe what you did, what you expect, and what happens?

**Comment by zozoh94** [comment]
Ok, thank you already for you help :+1: 

- I have a consumer for Server Side Events to send serialized data (reservation) on creation and update. Reservation are associated to an Environment and users have permissions or no permissions on it. So I use environment name as group name, when a user connect I subscribe him to groups he can manage. 

`from .inherits_consumers import AsyncHttpConsumer
import json
import asyncio
from django.conf import settings
from django_auth_ldap.backend import LDAPBackend

from .reservable import Environment

class NotifEnvironmentConsumer(AsyncHttpConsumer):
    async def handle(self, body):
        self.user = self.scope["user"]
        if not self.user:
            await self.send_response(401, b"Use credentials to authenticate (accessToken)", headers=[
                (b"Content-Type", b"text/plain"),
            ])
            return
        ldap_user = LDAPBackend().populate_user(self.user.username).ldap_user
        if settings.ADMIN_LDAP_GROUP in ldap_user.group_names:
            self.environments = Environment.all()
        else:
            self.environments = filter(
                lambda environment: environment.ldap_group_access in ldap_user.group_names,
                Environment.all()
            )
        headers = [
            (b"Cache-Control", b"no-cache"),
            (b"Content-Type", b"text/event-stream"),
            (b"Access-Control-Allow-Credentials", b"true"),
        ]
        for white in settings.CORS_ORIGIN_WHITELIST:
            headers.append((b"Access-Control-Allow-Origin", white.encode('utf-8')))
        for environment in self.environments:
            await self.channel_layer.group_add(environment.id, self.channel_name)
        await self.send_headers(headers=headers)
        payload = "event: send-authorized-environment-slugs\ndata: %s\n\n" % json.dumps(list(map(lambda e : e.slug, self.environments)))
        await self.send_body(payload.encode("utf-8"), more_body=True)
        payload = "event: send-channel-name\ndata: %s\n\n" % json.dumps(self.channel_name)
        await self.send_body(payload.encode("utf-8"), more_body=True)
        await asyncio.get_event_loop().create_task(self.keep_alive())
    async def keep_alive(self):
        await asyncio.sleep(60)
        payload = "event: keep-alive\ndata: \n\n"
        await self.send_body(payload.encode("utf-8"), more_body=True)
        asyncio.get_event_loop().create_task(self.keep_alive())
    async def disconnect(self):
        for environment in self.environments:
            async_to_sync(self.channel_layer.group_discard)(environment.id, self.channel_name)
    async def send_reservation(self, event):
        del event['type']
        payload = "event: send-reservation\ndata: %s\n\n" % json.dumps(event)
        await self.send_body(payload.encode("utf-8"), more_body=True)
`

I send event on models events from another server (container) that's what I can't use memory channel layer. Ex:
`@receiver(Reservation.status_changed_signal)
def status_changed_send(sender, reservation, original_status, **kwargs):
    channel_layer = get_channel_layer()
    async_to_sync(channel_layer.group_send)(
        reservation.reservable.id,
        {
            'type': 'send.reservation',
            'action': 'reservationUpdated',
            'reservation': ReservationSerializer(reservation).data,
            'reservable': ReservableDetail2Serializer(reservation.reservable).data
        }
    )
`

The problem is that when from my app or with curl I connect my SSE endpoint I receive "send-reservation" events only in one of each (first connected).

**Comment by adamhooper** [comment]
What happens if you delete the `del event['type']` line?

**Comment by zozoh94** [comment]
It works now ! Thank you a lot. How can you explain the error of this line ?

**Comment by adamhooper** [comment]
Each consumer runs a loop: it receives a message, then "dispatches" it based on `message["type"]`.

When a message is sent to multiple consumers, they all see the same message. So if Consumer 1 deletes `message["type"]`, then Consumer 2 won't see `message["type"]` -- so it won't dispatch the message.

Now that we've identified the problem, I'm wondering what fixes -- if any -- to employ.  (By my reading, `channels_redis` behaves the same way.) The obvious options:

* Queue messages as a [MappingProxyType](https://docs.python.org/3/library/types.html#types.MappingProxyType) -- so the line `del message["type"]` raises `TypeError` and you can find the problem easily. This helps discover _your_ error (which is surely the most common error); but unfortunately, it doesn't solve the broader problem. Consumers could still `del message["reservation"]["id"]`, for instance.
* Queue messages in msgpack format, and unpack them in `receive()`. That way each consumer can alter `message` without affecting other consumers' `message`. Unfortunately, this means unpacking each message twice -- once to queue it, and once when each consumer calls `receive()`.
* Add documentation to `channels_redis`, warning against `del message["type"]`. Unfortunately, users who don't read the docs are left in the lurch.
* Add documentation to `channels` proper, warning against `del message["type"]`. Unfortunately, users who don't read the docs are left in the lurch.

This would all be easier if Python had a `frozendict` type ... but it doesn't.

(Pro Tip: programming is easier if you never mutate function arguments. In your code, just send a message with `{"type": "send.reservation", "data": {"action": ..., "reservation": ..., "reservable": ...}}` -- and then you don't need to `del`.)

@zozoh94 Incidentally, my reading of `channels` suggests it should be raising a ValueError in some consumers: `"Incoming message has no 'type' attribute"`. Do you see this message in any logs?

**Comment by adamhooper** [comment]
After pondering for a few months, I've decided to close this issue without implementing any fixes. It is un-Pythonic to mutate function arguments. Hopefully, moving forward, affected users will be able to search online and find this issue and my earlier explanation.
