### ISSUE TITLE
Python3.8, aioamqp

### ISSUE THREAD

**Issue by ndavydovdev** [CJWorkbench/channels_rabbitmq#20]
Hello, counterparts! I want to notify you about new version of aioamqp which supports Python3.8 (https://github.com/Polyconseil/aioamqp/issues/210), can we update to this version? There were minor changes to support Python3.8

**Comment by ndavydovdev** [comment]
I've created pull request #21

**Comment by adamhooper** [comment]
Thank you for the pull request! This is looking good. I'm going to fiddle with Travis, trying to get it to test Python 3.7 and Python 3.8. If that works, I'll release a new patch version.

**Comment by adamhooper** [comment]
This isn't done -- I still need to fiddle with Travis.
