### ISSUE TITLE
RuntimeError: dictionary changed size during iteration when accessing local_groups

### ISSUE THREAD

**Issue by damianrusinek** [CJWorkbench/channels_rabbitmq#23]
The line 273 from `connection.py` (https://github.com/CJWorkbench/channels_rabbitmq/blob/master/channels_rabbitmq/connection.py#L273) raises an error when the channel dictionary is iterated and the `local_groups` is accessed.

I guess it is because you forgot to use `async with self._groups_lock:` when entering the `put_group` method.

Fix:
```
    async def _handle_message_background(
        self, channel, asgi_channel, group, data, delivery_tag
    ):
        """
        Deliver `data` to `asgi_channel` or `group`, then ack.
        See comment on `self._pending_puts`. To sum up: we need to schedule
        this code to run later, so we don't block aioamqp from handling network
        traffic.
        """
        # Put into _incoming_messages. This shouldn't raise anything, though
        # CancelledError is possible in theory. (CancelledError should not be
        # caught.)
        if asgi_channel:
            # Put the message. Back-pressure if
            # self._incoming_messages is at capacity.
            await self._incoming_messages.put_channel(asgi_channel, data)
        else:
            async with self._groups_lock: # <-----------------------------------------------------   Added this line
                await self._incoming_messages.put_group(group, data)

        await ack_message_if_we_can(channel, delivery_tag)
```

Error:
```
mar 04 18:30:03 daphne[24044]: File "/opt/app/environment/lib/python3.6/site-packages/channels_rabbitmq/connection.py", line 274,
mar 04 18:30:03 daphne[24044]: for asgi_channel in self.local_groups[group]:
mar 04 18:30:03 daphne[24044]: RuntimeError: dictionary changed size during iteration
```

**Comment by adamhooper** [comment]
Thank you for reporting this. It indeed looks like a problem...

... but I haven't seen this problem on production. Can you reproduce it reliably? If so, please share some code. Otherwise ... how often do you see it?

**Comment by damianrusinek** [comment]
I see it quite often when about 50 people are using the applications (so not that big number).
However I guess it is not a matter of volume but the concurrency and simultaneous access to `local_groups`. 
I think it happens when the `local_groups` is iterated to send messages and at the same some channel is added or removed to `local_groups`. In my case the sending messages is done by worker in separate thread.

**Comment by adamhooper** [comment]
Please describe "quite often".

Also: what are the consequences? Is this a disaster?

**Comment by damianrusinek** [comment]
I cannot give you the exact numbers like % of the requests. When I added that line the bug does not happen again.
The consequences are the exception raised which in my case was not caught (I usually do not catch RuntimeErrors :)) and the WS connection was closed.

**Comment by adamhooper** [comment]
k. I'm trying to stress-test and I can't make this bug happen. What versions of Python, Django, Channels, channels_rabbitmq are you running?

**Comment by adamhooper** [comment]
I've released v1.2.1 with the fix you suggest. I can't replicate the bug, but the bug _must_ exist.

**Comment by adamhooper** [comment]
(Thank you!)

**Comment by damianrusinek** [comment]
Ok, cool. Thanks.
If you still are trying to replicate it, try 2 threads where one is adding or removing a group channel an the other one is sending messages to the group (both infinite loops).

**Comment by adamhooper** [comment]
Thank you for the suggestion. But asyncio isn't thread-safe: you will get undefined behavior if you call any `channels_rabbitmq` methods from anything but the event-loop thread.

(For posterity): I wrote a unit test that added and removed 2,000 users while also sending 2,000 messages, on Python 3.7 and Python 3.8. I never hit this exception. I'm rather surprised -- we both agree, this _must_ have been a bug.
