### ISSUE TITLE
Connect/run on rabbitmq failed

### ISSUE THREAD

**Issue by dipesh2597** [CJWorkbench/channels_rabbitmq#24]
I am using django-channels with rabbitmq server.
Installed packages:
channels==2.4.0
channels-rabbitmq==1.2.1
rabbitmq_server-3.5.7

consumer.py:

`import asyncio
import json
from django.contrib.auth import get_user_model
from channels.consumer import AsyncConsumer
from channels.db import database_sync_to_async
from asgiref.sync import async_to_sync
class NotificationConsumer(AsyncConsumer):
    async def websocket_connect(self, event):
        print("connected", event)
        await self.send({
            "type": "websocket.accept"
        })
        user = self.scope['user'] 
        await self.send({
            "type": "websocket.send",
            "text": "Hello World"
        })
        print(self.channel_name)
        async_to_sync(self.channel_layer.group_add("gossip", self.channel_name))
        print(f"Added {self.channel_name} channel to gossip")

    async def websocket_received(self, event):
        print("receive", event)
    
    async def websocket_disconnect(self, event):
        print("disconnected", event) 
        await self.channel_layer.group_discard("gossip", self.channel_name)
        print(f"Removed {self.channel_name} channel to gossip")`

routing.py:

`from channels.routing import ProtocolTypeRouter, URLRouter
from channels.auth import AuthMiddlewareStack
from django.urls import path
from channels.security.websocket import AllowedHostsOriginValidator, OriginValidator
from problems.consumer import NotificationConsumer
import problems.routing

application = ProtocolTypeRouter({
    'websocket':AllowedHostsOriginValidator(
        AuthMiddlewareStack(
            URLRouter(
                [
                    path('', NotificationConsumer),
                ]
            )
        )
    )
})`

Channels setting in settings.py:

`ASGI_APPLICATION = 'codeyoda.routing.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_rabbitmq.core.RabbitmqChannelLayer",
        "CONFIG": {
            "host": "amqp://guest:guest@127.0.0.1/asgi",
            # "ssl_context": ... (optional)
        },
    },
}`

Error:
`(codeyodaEnv) vagrant@ubuntu-xenial:/vagrant/codeyoda-project$ python manage.py runserver 0.0.0.0:8080
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
July 21, 2020 - 12:07:56
Django version 2.2.4, using settings 'codeyoda.settings'
Starting ASGI/Channels version 2.4.0 development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
HTTP GET / 200 [0.24, 10.0.2.2:62960]
HTTP GET /static/css/base.css 304 [0.05, 10.0.2.2:62960]
HTTP GET /static/css/home.css 304 [0.04, 10.0.2.2:62961]
HTTP GET /static/css/tech-skills.css 304 [0.04, 10.0.2.2:62962]
HTTP GET /static/js/base.js 304 [0.05, 10.0.2.2:62963]
HTTP GET /static/images/logo.png 304 [0.03, 10.0.2.2:62963]
HTTP GET /uploads/static/images/PYTHON/python_JxDdwwZ.png 304 [0.05, 10.0.2.2:62962]
Not Found: /uploads/static/images/JAVASCRIPT/interview.png
HTTP GET /uploads/static/images/JAVASCRIPT/interview.png 404 [0.07, 10.0.2.2:62963]
Not Found: /uploads/static/images/hiring/basic_programming.jpg
HTTP GET /uploads/static/images/hiring/basic_programming.jpg 404 [0.08, 10.0.2.2:62961]
Not Found: /uploads/static/images/das/basic_programming.jpg
WebSocket HANDSHAKING / [10.0.2.2:62964]
HTTP GET /uploads/static/images/das/basic_programming.jpg 404 [0.11, 10.0.2.2:62960]
connected {'type': 'websocket.connect'}
WebSocket CONNECT / [10.0.2.2:62964]
admin
channels_LVrBroNbZmuB!rpQFvCasTpba
Added channels_LVrBroNbZmuB!rpQFvCasTpba channel to gossip
only PLAIN login_method is supported, falling back to AMQPLAIN
HTTP GET /static/images/favicon.ico 200 [0.02, 10.0.2.2:62960]
Connection lost exc=ConnectionResetError(104, 'Connection reset by peer')
Connect/run on RabbitMQ failed: AmqpClosedConnection(); will retry in 1.000000s
only PLAIN login_method is supported, falling back to AMQPLAIN
Connection lost exc=ConnectionResetError(104, 'Connection reset by peer')
Connect/run on RabbitMQ failed: AmqpClosedConnection(); will retry in 1.000000s
only PLAIN login_method is supported, falling back to AMQPLAIN
Connection lost exc=ConnectionResetError(104, 'Connection reset by peer')`

Followed [tutorial](https://pypi.org/project/channels-rabbitmq/) here

**Comment by adamhooper** [comment]
> Connection lost exc=ConnectionResetError(104, 'Connection reset by peer')

This log suggests the AMQP server has reset the connection. Let's sketch out a troubleshooting guide:

* Check there is a RabbitMQ server listening on that host+port (`telnet localhost 127.0.0.1 5672` should connect to the host)
* Check the AMQP version on the server (It must be RabbitMQ's default protocol, AMQP 0.9.1. AMQP 1.0 will not work.)
* Check that SSL is disabled on the RabbitMQ server (or configure the client to connect using SSL)

... that should be a good start for now. Please let me know how it goes!

**Comment by dipesh2597** [comment]
@adamhooper 

1. if I will downgrade amqp to 0.9.1 then it will not be compatible with kombu 4.6.8. 
2. I am using vagrant on my windows os it is working. But I am worried about my production AWS EC2 instance.
3. Telnet localhost command is not connecting with remote server

**Comment by adamhooper** [comment]
> 1. if I will downgrade amqp to 0.9.1 then it will not be compatible with kombu 4.6.8.

Kombu, too, uses AMQP 0.9.1. So if Kombu is working, I'm guessing your RabbitMQ server is set up with its default protocol, AMQP 0.9.1.

> 3. Telnet localhost command is not connecting with a remote server

This suggests you need to change the `"host"` in your `settings.py`. Try a URL that is accessible from your Django process. (If you're using Kombu already, then you can try the URL that Kombu uses.)

**Comment by adamhooper** [comment]
Closing because I've received no more feedback. If you're still having problems, please re-open!
