### ISSUE TITLE
using channel layer in a multi thereded script

### ISSUE THREAD

**Issue by ahmadpoorgholam** [CJWorkbench/channels_rabbitmq#40]
Hi, we have a script that uses concurrent.future thread pool executor, and each created thread, has its own event loop which will be sending data for the channel layer, but I'm facing `RuntimeError: The caller tried using channels_rabbitmq on a different event loop than the one it was initialized with`. how to get the right event loop to broadcast messages? 
thank you in advance

**Comment by adamhooper** [comment]
Don't run multiple event loops in a single process. We don't support it.

For more context: Python's Global Interpreter Lock (GIL) means only one thread per process executes Python code at any time. So a Python process can only ever process a single event at a time, no matter how many threads or event loops are running. Spreading events across multiple threads will increase the number of context switches and locks, slowing throughput.

Python releases the GIL when you reach a blocking operation; so with asyncio, never schedule blocking operations on the main thread. See [loop.run_in_executor()](https://docs.python.org/3/library/asyncio-eventloop.html#id14) for the standard means of scheduling blocking operations in thread pools. This gives you the only concurrency you can get, in a single process. And it means one event loop total -- which `channels_rabbitmq` supports.

You could also run a _process_ pool, with one event loop per process. That provides concurrency ... and `channels_rabbitmq` supports it.
