### ISSUE TITLE
Typo in Celery notes

### ISSUE THREAD

**Issue by ShaheedHaque** [CJWorkbench/channels_rabbitmq#43]
I think the documentation at https://github.com/CJWorkbench/channels_rabbitmq/blob/master/README.rst#publish-messages-from-celery has a typo. The quoted string here:
```python
producer.publish(
    msgpack.packb({
        "__asgi__group": group,
```
should be "\_\_asgi_group\_\_" if I am not mistaken.

**Comment by adamhooper** [comment]
Thank you! Fixed
