### ISSUE TITLE
Django Channels 4.0 Support

### ISSUE THREAD

**Issue by blocher** [CJWorkbench/channels_rabbitmq#44]
Thanks for this excellent package! Do you plan on supporting Django Channels 4.0?

**Comment by adamhooper** [comment]
I'll look into it. I expect the only thing to do is change version strings.
PRs welcome -- I'm pretty busy these days :)

**Comment by blocher** [comment]
sure i can give it a go. thanks!

**Comment by adamhooper** [comment]
https://pypi.org/project/channels-rabbitmq/4.0.1/

**Comment by blocher** [comment]
Thank you and sorry I didn't get back in time!
