### ISSUE TITLE
Update to asgiref 3

### ISSUE THREAD

**Issue by rakyi** [CJWorkbench/channels_rabbitmq#5]
This is needed to avoid conflicting dependencies with the latest Django Channels stack. I tried bumping the version locally and the basic functionality seems to work without any changes.

**Comment by adamhooper** [comment]
Heh -- I was actually working on the version bump as you filed this issue! I'll test it and then mark this closed.

**Comment by adamhooper** [comment]
`pip install channels_rabbitmq~=1.0.0`
