### ISSUE TITLE
Clarify usage with RabbitMQ cluster

### ISSUE THREAD

**Issue by rakyi** [CJWorkbench/channels_rabbitmq#6]
> To connect to a RabbitMQ cluster, use a DNS server to resolve a hostname to multiple IP addresses

We'd like to connect to a RabbitMQ cluster in ha-all mode. Does channels_rabbit reconnect automatically when the connection goes down, picking any online node from the IP addresses the host got resolved to? It would seem so based on this part of README, I'd just like to confirm it.

And thank you for your work!

**Comment by adamhooper** [comment]
Yep!

If you have the time, could you please suggest an edit to the docs that would clarify this?
